### ISSUE TITLE
ValueError ("'window_shape' is too large") 

### ISSUE THREAD

**Issue by LooTBonkHero** [pearsonkyle/brave_ad_clicker#1]
```
PS C:\Users\ME\Documents\brave_ad_clicker-main> python ad_clicker.py
windows
taking screen shot...
reshaping into windows...
Traceback (most recent call last):
  File "ad_clicker.py", line 69, in <module>
    im_windows = view_as_windows(im, tr.shape, step=args.stride)  # 4d array
  File "C:\Users\ME\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\util\shape.py", line 230, in 
view_as_windows
    raise ValueError("`window_shape` is too large")
ValueError: `window_shape` is too large
```

**Comment by TakingJester766** [comment]
Same problem as LooTBonkHero.

taking screen shot...
reshaping into windows...
Traceback (most recent call last):
  File "C:\Users\ME\downloads\brave_ad_clicker-main\brave_ad_clicker-main\ad_clicker.py", line 69, in <module>
    im_windows = view_as_windows(im, tr.shape, step=args.stride)  # 4d array
  File "C:\Users\ME\AppData\Local\Programs\Python\Python310\lib\site-packages\skimage\util\shape.py", line 229, in view_as_windows
    raise ValueError("`window_shape` is too large")
ValueError: `window_shape` is too large
